# Generated by Django 3.2 on 2021-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('attributes', models.JSONField(verbose_name='attributes')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_relevance_invalidation', models.BooleanField(default=False, verbose_name='Is timeout invalidation')),
                ('available_to', models.DateTimeField(verbose_name='Available to')),
                ('relevance_to', models.DateTimeField(verbose_name='Relevance to')),
            ],
            options={
                'verbose_name': 'Created cache',
                'verbose_name_plural': 'Created caches',
            },
        ),
    ]
